import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import ScrollTo from "./Components/ScrollTo";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "kelight Electrical",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Header />
        {children}
        <ScrollTo />
        <Footer />
      </body>
    </html>
  );
}
